SELECT P.NAME, PR.NAME, C.NAME 
FROM 
    PRODUCTS P 
INNER JOIN 
    PROVIDERS PR 
ON P.ID_PROVIDERS = PR.ID 
INNER JOIN CATEGORIES C 
ON P.id_categories = C.ID 
WHERE PR.NAME = 'Sansul SA' AND C.NAME = 'Imported';
